---

- name: Creating {{ repo_frontend_des_path }} directory
  file: dest={{ repo_frontend_des_path }} state=directory recurse=yes owner='www-data' group='www-data' mode=0755
  tags:
    - frontend-setup
    - frontend-repo-deploy
    - repositories-deploy

- name: Checking a directory to copy front-end app
  stat: path={{ repo_frontend_des_path }}
  register: frontend_dir
  tags:
    - frontend-setup
    - frontend-repo-deploy
    - repositories-deploy

- name: Cloning prossimo-app' repository from bitbucket
  git: dest={{ repo_frontend_des_path }} repo={{ git_frontend_repo }} accept_hostkey=yes key_file=/root/.ssh/id_rsa_prossimo update=yes
  when: frontend_dir.stat.isdir is defined and frontend_dir.stat.isdir and git_installed is defined and git_installed
  tags:
    - frontend-setup
    - frontend-repo-deploy
    - frontend-repo-update
    - repositories-deploy
    - repositories-update

- name: Configure nginx for prossimo
  template: src=prossimo.nginx.conf dest=/etc/nginx/sites-available force=yes
  tags:
    - frontend-setup
    - frontend-repo-deploy
    - frontend-repo-update
    - repositories-deploy
    - repositories-update
    - nginx-config

- file: src=/etc/nginx/sites-available/prossimo.nginx.conf dest=/etc/nginx/sites-enabled/prossimo.nginx.conf state=link
  tags:
    - frontend-setup
    - frontend-repo-deploy
    - frontend-repo-update
    - repositories-deploy
    - repositories-update
    - nginx-config
