---

- name: Installing nginx package
  apt: 
    pkg: '{{ item }}'
    state: 'present'
  with_items: nginx
  tags:
  - backend-setup
  - nginx-install

- name: Start the nginx service
  service: name=nginx state=started enabled=yes	
  tags:
  - backend-setup
  - nginx-install