---

- name: Installing PHP5.5 or later
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
  with_items: 
      - php5
      - php5-cli
      - php5-fpm
      - php-apc
      - php5-mysql
      - php5-pgsql
      - php5-sqlite
      - php5-tidy
      - php5-curl

  tags:
  - backend-setup
  - php5-install